<?php

/**
 * Implementation of hook_block_info().
 *
 * Provides a block which will contain the layer switcher icons.
 *
 * You will need to put this block in the correct region by going to:
 * Structure > Blocks in your browser.
 */
function openlayers_switcher_block_info() {
  $blocks['openlayers-switcher-block'] = array(
    'info' => t('openlayers-switcher-block'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 *
 * Renders a block which will contain the layer switcher icons.
 */
function openlayers_switcher_block_view($delta = '') {
  // http://www.jaypan.com/tutorial/adding-css-and-js-cached-block-drupal-7
  $block = array();
  switch ($delta) {
    case 'openlayers-switcher-block':
      $block = array(
        'content' => array(
          '#markup' => _openlayers_switcher_content(),
          '#attached' => array(
            // js commented out. jQuery changes not persisting when switchers
            // are clicked.
            // 'js' => array(
              // drupal_get_path('module', 'openlayers_switcher') . '/js/openlayers_switcher.js',
            // ),
            'css' => array(
              drupal_get_path('module', 'openlayers_switcher') . '/css/openlayers_switcher.css',
            ),
          )
        )
      );
      break;
  }
  return $block;
}

/**
 * custom html block
 * @return string
 *
 * Returns an empty div which will be populated using javascript with the layer
 * switcher icons.
 *
 * See the implementation of hook_js_alter() for how this is done.
 */
function _openlayers_switcher_content() {
  return "<div id='openlayers-switcher-block'></div>";
}

/**
 * Implements hook_openlayers_map_preprocess_alter().
 *
 * Ensures that the layerswitcher is maximized - this is important as we are 
 * moving it to a div which is outside the map.
 */
function openlayers_switcher_openlayers_map_preprocess_alter(&$map = array()) {
  $map['behaviors']['openlayers_behavior_layerswitcher']['maximizeDefault'] = 1;
}

/**
 * Implementation of hook_js_alter().
 *
 * IMPORTANT: We are using OpenLayers-2.11.
 *
 * The changes to the OpenLayers.js file 
 *
 * In the browser, go to /admin/structure/openlayers and ensure that the 
 * 'OpenLayers Source' textbox points at the correct OpenLayers version.
 *
 * This is important to note because we have altered the OpenLayers-2.11 version
 * of OpenLayers.js from line 2817 onwards to provide the HTML structure needed 
 * for our css to work as we wish with the layer switcher icons.
 *
 * Go to openlayers_switcher/OpenLayers-2.11/OpenLayers.js and search for 
 * lambeth.coop to see where the javascript code has been changed.
 *
 * Applying these same changes to OpenLayers-2.12 has been difficult. It's 
 * possible to build 2.12 so that it has a similar js to the 2.11 file.
 * @see http://docs.openlayers.org/library/deploying.html
 *
 * However I could not find how to make the click event work for the
 * aSwitcherBlock element. For that reason, we're sticking with OpenLayers-2.11
 * for now.
 *
 * I suspect a way forward for OpenLayers-2.12 and future versions is to go to:
 * OpenLayers-2.12/lib/OpenLayers/Control/LayerSwitcher.js
 * ... search for appendChild, make the changes in that file, then build.
 * @see http://docs.openlayers.org/library/deploying.html
 *
 * You should be able to run this diff command from the openlayers_switcher 
 * module folder to see the changes:
 *
 * diff ./OpenLayers-2.11/OpenLayers.js ../../../libraries/openlayers/OpenLayers-2.11/OpenLayers.js
 */
function openlayers_switcher_js_alter(&$javascript) {
  $ol_path = 'sites/all/libraries/openlayers/OpenLayers-2.11/OpenLayers.js';
  // drupal_js_defaults() needed.
  // http://drupal.org/node/1306584
  $my_ol_path = drupal_get_path('module', 'openlayers_switcher')
    . '/OpenLayers-2.11/OpenLayers.js';
  $javascript[$ol_path] = drupal_js_defaults($my_ol_path);
}

