<?php

/**
 * Implementation of hook_block_info().
 *
 * Provides a block which will contain the layer switcher icons.
 *
 * You will need to put this block in the correct region by going to:
 * Structure > Blocks in your browser.
 */
function openlayers_switcher_block_info() {
  $blocks['openlayers-switcher-block'] = array(
    'info' => t('openlayers-switcher-block'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 *
 * Renders a block which will contain the layer switcher icons.
 */
function openlayers_switcher_block_view($delta = '') {
  // http://www.jaypan.com/tutorial/adding-css-and-js-cached-block-drupal-7
  $block = array();
  switch ($delta) {
    case 'openlayers-switcher-block':
      $block = array(
        'content' => array(
          '#markup' => _openlayers_switcher_content(),
        )
      );
      break;
  }
  return $block;
}

/**
 * custom html block
 * @return string
 *
 * Returns an empty div which will be populated using javascript with the layer
 * switcher icons.
 *
 * See the implementation of hook_js_alter() for how this is done.
 */
function _openlayers_switcher_content() {
  return "<div id='openlayers-switcher-block'></div>";
}

/**
 * Implements hook_openlayers_map_preprocess_alter().
 *
 * Ensures that the layerswitcher is maximized - this is important as we are 
 * moving it to a div which is outside the map.
 */
function openlayers_switcher_openlayers_map_preprocess_alter(&$map = array()) {
  $map['behaviors']['openlayers_behavior_layerswitcher']['maximizeDefault'] = 1;
}

/**
 * Implementation of hook_js_alter().
 *
 * IMPORTANT: We are using OpenLayers-2.12.
 *
 * In the browser, go to /admin/structure/openlayers and ensure that the 
 * 'OpenLayers Source' textbox points at the correct OpenLayers version.
 *
 * TODO: Update this to 2.12
 * This is important to note because we have altered the OpenLayers-2.11 version
 * of OpenLayers.js at lines 2817 and 2818 to provide the structure needed for
 * our css to work as we wish with the layer switcher icons.
 *
 * You should be able to run this diff command from the openlayers_switcher 
 * module folder to see the changes:
 *
 * diff ./OpenLayers-2.12/OpenLayers.js ../../../libraries/openlayers/OpenLayers-2.12/OpenLayers.js
function openlayers_switcher_js_alter(&$javascript) {
  // Replace the OpenLayers 2.12 javascript file 
  $ol_path = 'sites/all/libraries/openlayers/OpenLayers-2.12/OpenLayers.js';
  // drupal_js_defaults() needed.
  // http://drupal.org/node/1306584
  $my_ol_path = drupal_get_path('module', 'openlayers_switcher')
    . '/OpenLayers-2.12/OpenLayers.js';
  $javascript[$ol_path] = drupal_js_defaults($my_ol_path);

  // Replace the openlayers_behavior_layerswitcher.js file.
  // Why? This is so that we can put the layerswitcher below the map.
  // This line puts the layerswitcher in the openlayers-switcher-block div:
  // options['div'] = OpenLayers.Util.getElement('openlayers-switcher-block');
 */

  /*
   * Commented out.
   * Why?
   * Adding the amended js here resulted in this error.
   * Uncaught TypeError: Cannot call method 'addBehavior' of undefined 
   *
   * In other words, Drupal.openlayers is not yet defined.
   * 
   * So, I've gone back to hacking openlayers module for now.
   * Amending the js file in the openlayers module.
  $layerswitcher_path =
    'sites/all/modules/openlayers/plugins/behaviors/openlayers_behavior_layerswitcher.js';
  $my_layerswitcher_path = drupal_get_path('module', 'openlayers_switcher')
    . '/openlayers_behavior_layerswitcher/openlayers_behavior_layerswitcher.js';
  $javascript[$layerswitcher_path] = drupal_js_defaults($layerswitcher_path);
   */
}
